AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function deployment (no IAM role creation)

Resources:

  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: app-8175-lambda
      Runtime: java21
      Handler: com.myapp.HelloHandler::handleRequest

      
      Role: arn:aws:iam::954257023384:role/app-8175-lambda-role

      MemorySize: 512
      Timeout: 15

      Code:
        S3Bucket: app-8175-s3-bucket
        S3Key: myapp.jar